name: Correção dos Projetos

on:
  push:
  workflow_dispatch:

jobs:
  projeto5-sistema-de-controle-de-producao:
    name: projeto5-sistema-de-controle-de-producao
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/projetos/projeto5-sistema-de-controle-de-producao
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto6-controle-de-producao-refatorado:
    name: projeto6-controle-de-producao-refatorado
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/projetos/projeto6-controle-de-producao-refatorado
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  projeto7-catalogo-de-filmes:
    name: projeto7-catalogo-de-filmes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/projetos/projeto7-catalogo-de-filmes
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test