name: Exercícios 4º bimestre

on:
  push:
  workflow_dispatch:

jobs:
  ex01-loop-while:
    name: ex01-loop-while
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex01-loop-while
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex02-loop-do-while:
    name: ex02-loop-do-while
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex02-loop-do-while
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex03-loop-for:
    name: ex03-loop-for
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex03-loop-for
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex04-array:
    name: ex04-array
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex04-array
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex05-operacao-array:
    name: ex05-operacao-array
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex05-operacao-array
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex06-loop-array:
    name: ex06-loop-array
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex06-loop-array
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex07-ordenacao-de-array:
    name: ex07-ordenacao-de-array
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex07-ordenacao-de-array
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex08-iteracao-de-array:
    name: ex08-iteracao-de-array
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex08-iteracao-de-array
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test