name: Testes por exerc√≠cio

on:
  push:
  workflow_dispatch:

jobs:
  ex01-ola-mundo:
    name: ex01-ola-mundo
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ex01-ola-mundo
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test

  ex02-variaveis:
    name: ex02-variaveis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ex02-variaveis
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test
